### ISSUE TITLE
Adding necessary pages

### ISSUE THREAD

**Issue by Rahaman002** [contentql/pin-realestate#1]

**Comment by Rahaman002** [comment]
- [x] Add neccessary files to pin-realestate repo related to homepage
- [x] Add scss 
- [x] Add images for homepage
- [x] update navbar
- [x] Add about and contact pages
- [x] Route to indivdual property
- [x] remove "blogs" from navbar

**Comment by julydeath** [comment]
created new branch ```mk-clinet-dashboard```

**Comment by julydeath** [comment]
- [x] Add Dashboard
- [x] Add Dashboard components
- [x] Add Login and Register form
- [x] Add agency
- [x] Add agents
- [x] Add faqs
- [x] Add compare
- [x] Add pricing
- [x] Add agency dynamic page
- [x] Add agent dynamic page
- [x] Add contact and about pages
- [x] Convert ```js``` to ```tsx```
- [x] Update navbar
- [x] Change routes in pages

**Comment by charanm927** [comment]
- [x] Update mobile menu
- [x] Remove unwanted components
- [x] Added home pages images
